# Generated by Django 4.1.7 on 2023-02-27 14:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uid',
                 models.UUIDField(default=uuid.uuid4,
                                  editable=False,
                                  primary_key=True,
                                  serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField(blank=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['modified', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'],
                               name='document_title_d37b4c_idx'),
        ),
    ]
