# Generated by Django 4.1.7 on 2023-02-27 18:33

from django.db import migrations, models

import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(
                blank=True, validators=[documents.validators.nodes_validator]),
        ),
    ]
