# Generated by Django 4.1.7 on 2023-02-28 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(validators=[documents.validators.nodes_validator]),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
